# Generated by Django 4.2.2 on 2023-06-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='codigos_demora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.PositiveIntegerField()),
                ('alpha', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('accountable', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('combustible', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='turnaround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fk_codigos_demora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.codigos_demora')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField()),
                ('cargo', models.CharField(max_length=50)),
                ('departameto', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_reg', models.CharField(max_length=50)),
                ('ac_type', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('lugar_salida', models.CharField(max_length=50)),
                ('lugar_destino', models.CharField(max_length=50)),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.DateTimeField()),
                ('ente_pagador', models.CharField(max_length=50)),
                ('numero_vuelo', models.BigIntegerField()),
                ('ETA', models.CharField(max_length=50)),
                ('ETD', models.CharField(max_length=50)),
                ('ATA', models.CharField(max_length=50)),
                ('ATD', models.CharField(max_length=50)),
                ('gate', models.CharField(max_length=50)),
                ('tipo_vuelo', models.CharField(max_length=50)),
                ('fk_aerolinea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aerolinea')),
                ('fk_maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.maquinaria')),
                ('fk_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plantilla')),
                ('fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='usuario_turnaround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_turnaround', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnaround')),
                ('fk_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fk_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=50)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('comentario', models.CharField(max_length=100)),
                ('fk_tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='maquinaria_turnaround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.maquinaria')),
                ('fk_turnaround', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnaround')),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('link', models.CharField(max_length=200)),
                ('fk_vuelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vuelo')),
            ],
        ),
    ]
