# Generated by Django 4.2.2 on 2023-06-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_fk_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='departameto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
    ]
