# Generated by Django 4.2.2 on 2023-06-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_correo_usuario_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
