# Generated by Django 4.2.2 on 2023-07-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtarea',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='subtarea',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='subtarea',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='subtarea',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='fk_maquinaria',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='fk_usuario',
        ),
        migrations.AddField(
            model_name='turnaround',
            name='fk_vuelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vuelo'),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('fk_subtarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subtarea')),
                ('fk_turnaround', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnaround')),
            ],
        ),
        migrations.CreateModel(
            name='HoraInicioFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('fk_subtarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subtarea')),
                ('fk_turnaround', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnaround')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('fk_subtarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subtarea')),
                ('fk_turnaround', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnaround')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('fk_subtarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subtarea')),
                ('fk_turnaround', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.turnaround')),
            ],
        ),
    ]
