# Generated by Django 4.2.2 on 2023-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_subtarea_comentario_remove_subtarea_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerolinea',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
