# Generated by Django 4.2.2 on 2023-07-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_aerolinea_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnaround',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turnaround',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
