# Generated by Django 4.2.2 on 2023-07-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_usuario_turnaround_fk_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subtarea',
            name='tipo',
        ),
        migrations.CreateModel(
            name='tipo_subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_subtarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subtarea')),
                ('fk_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='cantidad_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fk_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('fk_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plantilla')),
            ],
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='fk_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='fk_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipo'),
        ),
    ]
