# Generated by Django 4.2.2 on 2023-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_categoria_tipo_remove_maquinaria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos_demora',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
