# Generated by Django 4.2.2 on 2023-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_codigos_demora_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolinea',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='correo_secundario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='telefono_secundario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
