# Generated by Django 4.2.2 on 2023-08-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_aerolinea_ciudad_aerolinea_correo_secundario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
