# Generated by Django 4.2.2 on 2023-08-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_maquinaria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='imagen',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
