# Generated by Django 4.2.2 on 2023-08-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_ciudades_ciudades_destino_ciudades_salida_tipo_vuelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='ETA',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ETD',
            field=models.TimeField(),
        ),
    ]
