# Generated by Django 4.2.2 on 2023-08-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_vuelo_fecha_llegada_remove_vuelo_hora_llegada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='ATA',
            new_name='ETA_fecha',
        ),
        migrations.RenameField(
            model_name='vuelo',
            old_name='ATD',
            new_name='ETD_fecha',
        ),
    ]
