# Generated by Django 4.2.2 on 2023-09-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_ata_vuelo_eta_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnaround',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turnaround',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
