# Generated by Django 4.2.2 on 2023-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_turnaround_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='ATA',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='ATA_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='ATD',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='ATD_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
