# Generated by Django 4.2.2 on 2023-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_vuelo_ata_vuelo_ata_fecha_vuelo_atd_vuelo_atd_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='numero_vuelo',
            field=models.CharField(max_length=50),
        ),
    ]
