# Generated by Django 4.2.2 on 2023-09-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_vuelo_numero_vuelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='ETA',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ETA_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ETD',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ETD_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ac_reg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ac_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='ente_pagador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='gate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='numero_vuelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
