# Generated by Django 4.2.2 on 2023-09-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_vuelo_eta_alter_vuelo_eta_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ciudades',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ciudades',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ciudades',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='codigo_IATA',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='codigo_OACI',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipo_servicio'),
        ),
    ]
