# Generated by Django 4.2.2 on 2023-09-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tipo_servicio_remove_ciudades_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudades',
            old_name='ciudad',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='ciudades',
            old_name='codigo_IATA',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='ciudades',
            name='codigo_OACI',
        ),
        migrations.RemoveField(
            model_name='ciudades',
            name='pais',
        ),
    ]
