# Generated by Django 4.2.2 on 2023-09-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_ciudad_ciudades_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='lugar_destino',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='lugar_salida',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='stn',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='lugar_destino',
            field=models.ManyToManyField(blank=True, related_name='lugar_destino', to='api.ciudades'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='lugar_salida',
            field=models.ManyToManyField(blank=True, related_name='lugar_salida', to='api.ciudades'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='stn',
            field=models.ManyToManyField(blank=True, related_name='stn', to='api.ciudades'),
        ),
    ]
