# Generated by Django 4.2.2 on 2023-09-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_vuelo_icao_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudades',
            name='codigo_oaci',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
