# Generated by Django 4.2.2 on 2023-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ciudades_codigo_oaci'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudades',
            name='aeropuerto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
