# Generated by Django 4.2.2 on 2023-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_ciudades_aeropuerto_ciudades_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='aeropuerto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
