# Generated by Django 4.2.2 on 2023-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_maquinaria_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria_historial',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria_historial',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
