# Generated by Django 4.2.2 on 2023-10-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_maquinaria_historial_fk_turnaround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_turnaround',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario_turnaround',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario_turnaround',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
