# Generated by Django 4.2.2 on 2023-10-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_usuario_turnaround_fecha_usuario_turnaround_hora_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_turnaround',
            name='fk_user',
        ),
        migrations.AddField(
            model_name='usuario_turnaround',
            name='fk_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
