# Generated by Django 4.2.2 on 2024-01-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_cargo_departamento_remove_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinarias/'),
        ),
    ]
