# Generated by Django 4.2.2 on 2024-01-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_maquinaria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='link',
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='turnaround/'),
        ),
    ]
