# Generated by Django 4.2.2 on 2024-04-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rol_usuario_fk_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_turnaround',
            name='asistencia',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
